name: Docker Image CI

on:
  push:
    branches: [ "main" ]  # Ana branch'e yapılan push işlemiyle tetiklenir
  pull_request:
    branches: [ "main" ]  # Main branch'e yapılacak pull request ile tetiklenir

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions için Ubuntu ortamı kullanıyoruz

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Reponuzu çekiyoruz

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Docker Buildx kurulumunu yapıyoruz

    - name: Cache Docker layers
      uses: actions/cache@v3  # Docker katmanlarını önbelleğe almak için v3 sürümünü kullanıyoruz
      with:
        path: /tmp/.buildx-cache  # Docker'ın cache verilerini saklıyoruz
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build the Docker image from Dockerfile
      run: |
        docker build -f Dockerfile -t elifarslancelik/ERIC:latest .  # Proje adı 'ERIC', doğru şekilde tag'liyoruz

    - name: Run the Docker container
      run: |
        docker run -d -p 8080:80 elifarslancelik/ERIC:latest  # Aynı tag'i kullanarak container'ı başlatıyoruz
